name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # You can specify your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        permissions:
          contents: write
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
